---
- debug:
    msg: "oah-update of oah.users"
# update oah user name

# update oah user gitlab key

# update oah user github key

# update oah env user name

# update oah env user gitlab key

# update oah env user github key

# check OAH_USER set

# check OAH_ENV_USER set

# check oah env user data in oah data/users

# display oah env user and oah user details
